name: Deploy jupyterhub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    env:
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ env.SERVER_SSH_KEY }}
      
      - name: Copy source code to server
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SERVER_SSH_KEY }}
          port: 22
          source: "."
          target: "~/jupyterhub-fenicsx/"
      
      - name: Build and deploy Docker container on server
        run: |
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST << 'EOF'
            cd ~/jupyterhub-fenicsx
            
            # Останавливаем и удаляем старый контейнер (если существует)
            if sudo docker ps -a --format '{{.Names}}' | grep -Eq '^jupyterhub-fenicsx-container$'; then
              echo "Stopping and removing existing container..."
              sudo docker stop jupyterhub-fenicsx-container || true
              sudo docker rm jupyterhub-fenicsx-container || true
            fi
            
            # Удаляем старый образ (опционально, освобождает место)
            if sudo docker images | grep -q jupyterhub-fenicsx; then
              echo "Removing old image..."
              sudo docker rmi jupyterhub-fenicsx || true
            fi
            
            # Собираем новый образ
            echo "Building new image..."
            sudo docker build -t jupyterhub-fenicsx .
            
            # Запускаем новый контейнер
            echo "Starting new container..."
            sudo docker run -d --name jupyterhub-fenicsx-container -p 8050:8000 --restart=always jupyterhub-fenicsx
            
            # Проверяем статус
            echo "Container status:"
            sudo docker ps | grep jupyterhub-fenicsx-container
          EOF
